<?php


namespace Trial\CoffeeMachine\Tests\Unit\Http\Controllers;


use PHPUnit\Framework\TestCase;

class CoffeeMachineOrderControllerTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}
