#!/usr/bin/env bash

docker build docker/images/angular-cli -t coffee-machine.ng
docker build docker/images/php -t coffee-machine.php
docker network create --driver=bridge --subnet=172.50.0.0/24 coffee-machine_net

docker build docker/images/mysql -t coffee-machine.mysql
docker-compose up -d
